// Copyright 2017-2026 @pezkuwi/ui-shared authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/ui-shared', path: 'auto', type: 'auto', version: '3.17.1' };
