// Copyright 2017-2026 @pezkuwi/vue-identicon authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/vue-identicon', path: 'auto', type: 'auto', version: '3.16.6' };
