// Copyright 2017-2026 @pezkuwi/react-qr authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/react-qr', path: 'auto', type: 'auto', version: '3.16.8' };
