// Copyright 2017-2026 @pezkuwi/react-identicon authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as settingsInfo } from '@pezkuwi/ui-settings/packageInfo';
import { packageInfo as sharedInfo } from '@pezkuwi/ui-shared/packageInfo';
import { detectPackage } from '@pezkuwi/util';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [settingsInfo, sharedInfo]);
